from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from watchlist_signal_bot.settings import load_yaml_file

HEADER = """# This file is generated from config/github_actions.yml.
# Run `python -m watchlist_signal_bot.github_actions` after changing that config.
# Do not edit this file manually.
"""

DEFAULT_MARKET_CHOICES = ["ALL", "KR", "US"]

DEFAULT_WORKFLOW_CONFIG: dict[str, dict[str, Any]] = {
    "daily": {
        "file": ".github/workflows/daily.yml",
        "name": "Daily Signal Bot",
        "permissions": {
            "contents": "read",
            "pages": "write",
            "id-token": "write",
        },
        "concurrency": {
            "group": "daily-signal-bot-${{ github.ref }}",
            "cancel-in-progress": False,
        },
        "dispatch_inputs": {
            "market": {
                "description": "Optional market filter",
                "required": False,
                "type": "choice",
                "options": DEFAULT_MARKET_CHOICES,
            },
            "dry_run": {
                "description": "Skip Telegram delivery",
                "required": False,
                "type": "boolean",
            },
            "publish_pages": {
                "description": "Deploy HTML report to GitHub Pages",
                "required": False,
                "type": "boolean",
            },
        },
        "cli": {
            "market_env": "MARKET",
            "dry_run_env": "DRY_RUN",
        },
        "secret_env": {
            "TELEGRAM_BOT_TOKEN": "${{ secrets.TELEGRAM_BOT_TOKEN }}",
            "TELEGRAM_CHAT_ID": "${{ secrets.TELEGRAM_CHAT_ID }}",
        },
        "runtime_artifact": {
            "name": "signal-bot-artifacts",
            "paths": ["artifacts", "data/prices"],
        },
        "pages": {
            "enabled": True,
            "public_dir": "public",
            "bundle_files": [
                {"source": "artifacts/report.html", "target": "public/index.html"},
                {"source": "artifacts/report.json", "target": "public/report.json"},
                {"source": "artifacts/signals_daily.csv", "target": "public/signals_daily.csv"},
                {
                    "source": "artifacts/signal_history.csv",
                    "target": "public/signal_history.csv",
                },
            ],
            "deploy_condition": (
                "${{ github.event_name == 'schedule' "
                "|| github.event.inputs.publish_pages != 'false' }}"
            ),
        },
    },
    "manual": {
        "file": ".github/workflows/manual.yml",
        "name": "Manual Signal Bot Test",
        "permissions": {
            "contents": "read",
            "pages": "write",
            "id-token": "write",
        },
        "dispatch_inputs": {
            "symbol": {
                "description": "Optional single symbol filter",
                "required": False,
                "type": "string",
            },
            "group": {
                "description": "Optional group filter",
                "required": False,
                "type": "string",
            },
            "market": {
                "description": "Optional market filter",
                "required": False,
                "type": "choice",
                "options": DEFAULT_MARKET_CHOICES,
            },
            "dry_run": {
                "description": "Skip Telegram delivery",
                "required": False,
                "type": "boolean",
            },
            "publish_pages": {
                "description": "Deploy generated report to GitHub Pages",
                "required": False,
                "type": "boolean",
            },
        },
        "cli": {
            "symbol_env": "SYMBOL",
            "group_env": "GROUP",
            "market_env": "MARKET",
            "dry_run_env": "DRY_RUN",
        },
        "secret_env": {
            "TELEGRAM_BOT_TOKEN": "${{ secrets.TELEGRAM_BOT_TOKEN }}",
            "TELEGRAM_CHAT_ID": "${{ secrets.TELEGRAM_CHAT_ID }}",
        },
        "runtime_artifact": {
            "name": "manual-signal-bot-artifacts",
            "paths": ["artifacts"],
        },
        "pages": {
            "enabled": True,
            "public_dir": "public",
            "prepare_condition": "${{ github.event.inputs.publish_pages == 'true' }}",
            "deploy_condition": "${{ github.event.inputs.publish_pages == 'true' }}",
            "bundle_files": [
                {"source": "artifacts/report.html", "target": "public/index.html"},
                {"source": "artifacts/report.json", "target": "public/report.json"},
            ],
        },
    },
}


def load_github_actions_config(
    *,
    root_dir: Path,
    config_path: Path | None = None,
) -> dict[str, Any]:
    return load_yaml_file(config_path or root_dir / "config" / "github_actions.yml")


def render_workflows(config: dict[str, Any]) -> dict[str, str]:
    return {
        workflow["file"]: render_workflow(workflow=workflow)
        for workflow in build_workflows(config).values()
    }


def sync_workflows(
    *,
    root_dir: Path,
    config_path: Path | None = None,
    check: bool = False,
) -> list[Path]:
    config = load_github_actions_config(root_dir=root_dir, config_path=config_path)
    rendered = render_workflows(config)
    changed: list[Path] = []
    for relative_path, content in rendered.items():
        target = root_dir / relative_path
        existing = target.read_text(encoding="utf-8") if target.exists() else None
        if existing != content:
            changed.append(target)
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
    return changed


def build_workflows(config: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        "daily": _build_daily_workflow(config.get("daily", {})),
        "manual": _build_manual_workflow(config.get("manual", {})),
    }


def render_workflow(*, workflow: dict[str, Any]) -> str:
    lines: list[str] = [HEADER.rstrip(), "", f'name: "{workflow["name"]}"', "", "on:"]
    lines.extend(_render_on_block(workflow))
    lines.append("")
    lines.append("permissions:")
    lines.extend(_render_mapping(workflow_value=workflow["permissions"], indent=1))

    if workflow.get("concurrency"):
        lines.append("")
        lines.append("concurrency:")
        lines.extend(_render_mapping(workflow_value=workflow["concurrency"], indent=1))

    lines.append("")
    lines.append("jobs:")
    lines.extend(_render_jobs(workflow=workflow))
    return "\n".join(lines).rstrip() + "\n"


def _render_jobs(*, workflow: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    lines.extend(_render_build_job(workflow=workflow))
    lines.extend(_render_pages_deploy_job(workflow=workflow))
    return lines


def _render_on_block(workflow: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    schedules = workflow.get("schedule", [])
    if schedules:
        lines.append("  schedule:")
        for cron in schedules:
            lines.append(f'    - cron: "{cron}"')

    dispatch_inputs = workflow.get("dispatch_inputs", {})
    if dispatch_inputs:
        lines.append("  workflow_dispatch:")
        lines.append("    inputs:")
        for key, definition in dispatch_inputs.items():
            lines.append(f"      {key}:")
            lines.append(f'        description: "{definition["description"]}"')
            lines.append(f"        required: {_yaml_bool(definition.get('required', False))}")
            if "default" in definition:
                lines.append(f"        default: {_yaml_scalar(definition['default'])}")
            lines.append(f'        type: "{definition["type"]}"')
            options = definition.get("options", [])
            if options:
                lines.append("        options:")
                for option in options:
                    lines.append(f"          - {option}")
    return lines


def _render_build_job(*, workflow: dict[str, Any]) -> list[str]:
    lines = [
        "  build:",
        '    runs-on: "ubuntu-latest"',
        "    env:",
    ]
    env = dict(workflow.get("env", {}))
    env.update(workflow.get("secret_env", {}))
    for key, value in env.items():
        lines.append(f"      {key}: {value}")

    lines.extend(
        [
            "    steps:",
            '      - name: "Checkout"',
            '        uses: "actions/checkout@v4"',
            "",
            '      - name: "Setup Python"',
            '        uses: "actions/setup-python@v5"',
            "        with:",
            '          python-version: "3.12"',
            "",
            '      - name: "Setup uv"',
            '        uses: "astral-sh/setup-uv@v5"',
            "        with:",
            '          version: "0.6.11"',
            "",
            '      - name: "Install dependencies"',
            '        run: "uv sync --group dev"',
            "",
        ]
    )
    lines.extend(_render_run_step(workflow=workflow))
    lines.extend(_render_pages_setup_step(workflow=workflow))
    lines.extend(_render_pages_prepare_step(workflow=workflow))
    lines.extend(_render_pages_artifact_step(workflow=workflow))
    lines.extend(_render_runtime_artifact_step(workflow=workflow))
    return lines


def _render_run_step(*, workflow: dict[str, Any]) -> list[str]:
    cli = workflow.get("cli", {})
    lines = [
        f'      - name: "Run {workflow["name"]}"',
        '        shell: "bash"',
        "        run: |",
        "          set -euo pipefail",
        "          cmd=(uv run python -m watchlist_signal_bot.main)",
    ]

    if cli.get("market_env"):
        env_name = cli["market_env"]
        lines.extend(
            [
                f'          if [[ "${{{env_name}}}" != "" && "${{{env_name}}}" != "ALL" ]]; then',
                f'            cmd+=(--market "${{{env_name}}}")',
                "          fi",
            ]
        )
    if cli.get("group_env"):
        env_name = cli["group_env"]
        lines.extend(
            [
                f'          if [[ -n "${{{env_name}}}" ]]; then',
                f'            cmd+=(--group "${{{env_name}}}")',
                "          fi",
            ]
        )
    if cli.get("symbol_env"):
        env_name = cli["symbol_env"]
        lines.extend(
            [
                f'          if [[ -n "${{{env_name}}}" ]]; then',
                f'            cmd+=(--symbol "${{{env_name}}}")',
                "          fi",
            ]
        )

    dry_run_env = cli.get("dry_run_env")
    if dry_run_env:
        dry_run_condition = (
            f'          if [[ "${{{dry_run_env}}}" == "true"'
            ' || -z "${TELEGRAM_BOT_TOKEN}"'
            ' || -z "${TELEGRAM_CHAT_ID}" ]]; then'
        )
        lines.extend(
            [
                dry_run_condition,
                "            cmd+=(--dry-run)",
                "          fi",
            ]
        )
    lines.append('          "${cmd[@]}"')
    lines.append("")
    return lines


def _render_pages_prepare_step(*, workflow: dict[str, Any]) -> list[str]:
    pages = workflow.get("pages", {})
    if not pages.get("enabled"):
        return []

    public_dir = pages["public_dir"]
    lines = ['      - name: "Prepare Pages bundle"']
    bundle_condition = _pages_bundle_condition(pages)
    if bundle_condition:
        lines.append(f"        if: {bundle_condition}")
    lines.extend(
        [
            "        run: |",
            f"          mkdir -p {public_dir}",
        ]
    )
    for bundle in pages.get("bundle_files", []):
        lines.append(f"          cp {bundle['source']} {bundle['target']}")
    lines.append(f"          touch {public_dir}/.nojekyll")
    lines.append("")
    return lines


def _render_pages_setup_step(*, workflow: dict[str, Any]) -> list[str]:
    pages = workflow.get("pages", {})
    if not pages.get("enabled"):
        return []

    lines = ['      - name: "Setup GitHub Pages"']
    bundle_condition = _pages_bundle_condition(pages)
    if bundle_condition:
        lines.append(f"        if: {bundle_condition}")
    lines.extend(
        [
            '        uses: "actions/configure-pages@v5"',
            "",
        ]
    )
    return lines


def _render_pages_artifact_step(*, workflow: dict[str, Any]) -> list[str]:
    pages = workflow.get("pages", {})
    if not pages.get("enabled"):
        return []

    lines = ['      - name: "Upload Pages artifact"']
    bundle_condition = _pages_bundle_condition(pages)
    if bundle_condition:
        lines.append(f"        if: {bundle_condition}")
    lines.extend(
        [
            '        uses: "actions/upload-pages-artifact@v3"',
            "        with:",
            f'          path: "{pages["public_dir"]}"',
            "",
        ]
    )
    return lines


def _render_runtime_artifact_step(*, workflow: dict[str, Any]) -> list[str]:
    artifact = workflow["runtime_artifact"]
    lines = [
        '      - name: "Upload runtime artifacts"',
        '        uses: "actions/upload-artifact@v4"',
        "        with:",
        f'          name: "{artifact["name"]}"',
        "          path: |",
    ]
    for path in artifact["paths"]:
        lines.append(f"            {path}")
    lines.append("")
    return lines


def _render_pages_deploy_job(*, workflow: dict[str, Any]) -> list[str]:
    pages = workflow.get("pages", {})
    if not pages.get("enabled"):
        return []

    lines = [
        "  deploy:",
        '    runs-on: "ubuntu-latest"',
        '    needs: "build"',
    ]
    if pages.get("deploy_condition"):
        lines.append(f"    if: {pages['deploy_condition']}")
    lines.extend(
        [
            "    environment:",
            '      name: "github-pages"',
            '      url: "${{ steps.deployment.outputs.page_url }}"',
            "    steps:",
            '      - name: "Deploy to GitHub Pages"',
            '        id: "deployment"',
            '        uses: "actions/deploy-pages@v4"',
            "",
        ]
    )
    return lines


def _pages_bundle_condition(pages: dict[str, Any]) -> str | None:
    return pages.get("prepare_condition") or pages.get("deploy_condition")


def _build_daily_workflow(config: dict[str, Any]) -> dict[str, Any]:
    market = _market_option(config.get("options", {}).get("market", {}), default="ALL")
    dry_run = _bool_option(config.get("options", {}).get("dry_run", {}), default=False)
    publish_pages = _bool_option(config.get("options", {}).get("publish_pages", {}), default=True)

    workflow = _deep_copy(DEFAULT_WORKFLOW_CONFIG["daily"])
    workflow["schedule"] = list(config.get("schedule", []))
    workflow["dispatch_inputs"]["market"]["default"] = market["default"]
    workflow["dispatch_inputs"]["market"]["options"] = market["choices"]
    workflow["dispatch_inputs"]["dry_run"]["default"] = dry_run
    workflow["dispatch_inputs"]["publish_pages"]["default"] = publish_pages
    workflow["env"] = {
        "MARKET": f"${{{{ github.event.inputs.market || '{market['default']}' }}}}",
        "DRY_RUN": f"${{{{ github.event.inputs.dry_run || '{_bool_string(dry_run)}' }}}}",
    }
    return workflow


def _build_manual_workflow(config: dict[str, Any]) -> dict[str, Any]:
    market = _market_option(config.get("options", {}).get("market", {}), default="ALL")
    dry_run = _bool_option(config.get("options", {}).get("dry_run", {}), default=True)
    publish_pages = _bool_option(config.get("options", {}).get("publish_pages", {}), default=False)

    workflow = _deep_copy(DEFAULT_WORKFLOW_CONFIG["manual"])
    workflow["dispatch_inputs"]["market"]["default"] = market["default"]
    workflow["dispatch_inputs"]["market"]["options"] = market["choices"]
    workflow["dispatch_inputs"]["dry_run"]["default"] = dry_run
    workflow["dispatch_inputs"]["publish_pages"]["default"] = publish_pages
    workflow["env"] = {
        "SYMBOL": "${{ github.event.inputs.symbol }}",
        "GROUP": "${{ github.event.inputs.group }}",
        "MARKET": f"${{{{ github.event.inputs.market || '{market['default']}' }}}}",
        "DRY_RUN": f"${{{{ github.event.inputs.dry_run || '{_bool_string(dry_run)}' }}}}",
    }
    return workflow


def _render_mapping(*, workflow_value: dict[str, Any], indent: int) -> list[str]:
    lines: list[str] = []
    prefix = "  " * indent
    for key, value in workflow_value.items():
        if isinstance(value, bool):
            lines.append(f"{prefix}{key}: {_yaml_bool(value)}")
        else:
            lines.append(f"{prefix}{key}: {_yaml_scalar(value)}")
    return lines


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return _yaml_bool(value)
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace('"', '\\"')
    return f'"{text}"'


def _yaml_bool(value: bool) -> str:
    return "true" if value else "false"


def _bool_string(value: bool) -> str:
    return "true" if value else "false"


def _market_option(option: dict[str, Any], *, default: str) -> dict[str, Any]:
    choices = list(option.get("choices", DEFAULT_MARKET_CHOICES))
    normalized_default = str(option.get("default", default))
    if normalized_default not in choices:
        choices = [
            normalized_default,
            *[choice for choice in choices if choice != normalized_default],
        ]
    return {
        "default": normalized_default,
        "choices": choices,
    }


def _bool_option(option: dict[str, Any], *, default: bool) -> bool:
    value = option.get("default", default)
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "on"}
    return bool(value)


def _deep_copy(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _deep_copy(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_deep_copy(item) for item in value]
    return value


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate GitHub Actions workflows from config")
    parser.add_argument("--root-dir", default=".", help="Project root directory")
    parser.add_argument("--config", help="Path to config/github_actions.yml")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether workflows are up to date",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root_dir = Path(args.root_dir).resolve()
    config_path = Path(args.config).resolve() if args.config else None
    changed = sync_workflows(root_dir=root_dir, config_path=config_path, check=args.check)
    if args.check and changed:
        for path in changed:
            print(f"Out of date: {path.relative_to(root_dir)}")
        return 1
    for path in changed:
        print(f"Updated: {path.relative_to(root_dir)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
