from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from watchlist_signal_bot.settings import load_yaml_file

HEADER = """# This file is generated from config/github_actions.yml.
# Run `python -m watchlist_signal_bot.github_actions` after changing that config.
# Do not edit this file manually.
"""


def load_github_actions_config(
    *,
    root_dir: Path,
    config_path: Path | None = None,
) -> dict[str, Any]:
    return load_yaml_file(config_path or root_dir / "config" / "github_actions.yml")


def render_workflows(config: dict[str, Any]) -> dict[str, str]:
    shared = config["shared"]
    return {
        workflow_config["file"]: render_workflow(shared=shared, workflow=workflow_config)
        for workflow_config in config["workflows"].values()
    }


def sync_workflows(
    *,
    root_dir: Path,
    config_path: Path | None = None,
    check: bool = False,
) -> list[Path]:
    config = load_github_actions_config(root_dir=root_dir, config_path=config_path)
    rendered = render_workflows(config)
    changed: list[Path] = []
    for relative_path, content in rendered.items():
        target = root_dir / relative_path
        existing = target.read_text(encoding="utf-8") if target.exists() else None
        if existing != content:
            changed.append(target)
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
    return changed


def render_workflow(*, shared: dict[str, Any], workflow: dict[str, Any]) -> str:
    lines: list[str] = [HEADER.rstrip(), "", f'name: "{workflow["name"]}"', "", "on:"]
    lines.extend(_render_on_block(workflow))
    lines.append("")
    lines.append("permissions:")
    lines.extend(_render_mapping(workflow_value=shared["permissions"], indent=1))

    if workflow.get("concurrency"):
        lines.append("")
        lines.append("concurrency:")
        lines.extend(_render_mapping(workflow_value=workflow["concurrency"], indent=1))

    lines.append("")
    lines.append("jobs:")
    lines.extend(_render_build_job(shared=shared, workflow=workflow))
    if workflow.get("pages", {}).get("enabled"):
        lines.extend(_render_deploy_job(shared=shared, workflow=workflow))
    return "\n".join(lines).rstrip() + "\n"


def _render_on_block(workflow: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    schedules = workflow.get("schedule", [])
    if schedules:
        lines.append("  schedule:")
        for cron in schedules:
            lines.append(f'    - cron: "{cron}"')

    dispatch_inputs = workflow.get("dispatch_inputs", {})
    if dispatch_inputs:
        lines.append("  workflow_dispatch:")
        lines.append("    inputs:")
        for key, definition in dispatch_inputs.items():
            lines.append(f"      {key}:")
            lines.append(f'        description: "{definition["description"]}"')
            lines.append(f"        required: {_yaml_bool(definition.get('required', False))}")
            if "default" in definition:
                lines.append(f"        default: {_yaml_scalar(definition['default'])}")
            lines.append(f'        type: "{definition["type"]}"')
            options = definition.get("options", [])
            if options:
                lines.append("        options:")
                for option in options:
                    lines.append(f"          - {option}")
    return lines


def _render_build_job(*, shared: dict[str, Any], workflow: dict[str, Any]) -> list[str]:
    lines = [
        "  build:",
        f'    runs-on: "{shared["runs_on"]}"',
        "    env:",
    ]
    env = dict(workflow.get("env", {}))
    env.update(shared.get("secret_env", {}))
    for key, value in env.items():
        lines.append(f"      {key}: {value}")

    lines.extend(
        [
            "    steps:",
            '      - name: "Checkout"',
            '        uses: "actions/checkout@v4"',
            "",
            '      - name: "Setup Python"',
            '        uses: "actions/setup-python@v5"',
            "        with:",
            f'          python-version: "{shared["python_version"]}"',
            "",
            '      - name: "Setup uv"',
            '        uses: "astral-sh/setup-uv@v5"',
            "        with:",
            f'          version: "{shared["uv_version"]}"',
            "",
            '      - name: "Install dependencies"',
            f'        run: "{shared["install_command"]}"',
            "",
        ]
    )
    lines.extend(_render_run_step(shared=shared, workflow=workflow))
    lines.extend(_render_pages_prepare_step(shared=shared, workflow=workflow))
    lines.extend(_render_runtime_artifact_step(workflow=workflow))
    lines.extend(_render_pages_upload_step(shared=shared, workflow=workflow))
    return lines


def _render_run_step(*, shared: dict[str, Any], workflow: dict[str, Any]) -> list[str]:
    cli = workflow.get("cli", {})
    lines = [
        f'      - name: "Run {workflow["name"]}"',
        '        shell: "bash"',
        "        run: |",
        "          set -euo pipefail",
        f'          cmd=(uv run python -m {shared["command_module"]})',
    ]

    if cli.get("market_env"):
        env_name = cli["market_env"]
        lines.extend(
            [
                f'          if [[ "${{{env_name}}}" != "" && "${{{env_name}}}" != "ALL" ]]; then',
                f'            cmd+=(--market "${{{env_name}}}")',
                "          fi",
            ]
        )
    if cli.get("group_env"):
        env_name = cli["group_env"]
        lines.extend(
            [
                f'          if [[ -n "${{{env_name}}}" ]]; then',
                f'            cmd+=(--group "${{{env_name}}}")',
                "          fi",
            ]
        )
    if cli.get("symbol_env"):
        env_name = cli["symbol_env"]
        lines.extend(
            [
                f'          if [[ -n "${{{env_name}}}" ]]; then',
                f'            cmd+=(--symbol "${{{env_name}}}")',
                "          fi",
            ]
        )

    dry_run_env = cli.get("dry_run_env")
    if dry_run_env:
        dry_run_condition = (
            f'          if [[ "${{{dry_run_env}}}" == "true"'
            ' || -z "${TELEGRAM_BOT_TOKEN}"'
            ' || -z "${TELEGRAM_CHAT_ID}" ]]; then'
        )
        lines.extend(
            [
                dry_run_condition,
                "            cmd+=(--dry-run)",
                "          fi",
            ]
        )
    lines.append('          "${cmd[@]}"')
    lines.append("")
    return lines


def _render_pages_prepare_step(*, shared: dict[str, Any], workflow: dict[str, Any]) -> list[str]:
    pages = workflow.get("pages", {})
    if not pages.get("enabled"):
        return []

    public_dir = shared["pages"]["public_dir"]
    lines = ['      - name: "Prepare Pages bundle"']
    if pages.get("prepare_condition"):
        lines.append(f"        if: {pages['prepare_condition']}")
    lines.extend(
        [
            "        run: |",
            f"          mkdir -p {public_dir}",
        ]
    )
    for bundle in pages.get("bundle_files", []):
        lines.append(f"          cp {bundle['source']} {bundle['target']}")
    lines.append("")
    return lines


def _render_runtime_artifact_step(*, workflow: dict[str, Any]) -> list[str]:
    artifact = workflow["runtime_artifact"]
    lines = [
        '      - name: "Upload runtime artifacts"',
        '        uses: "actions/upload-artifact@v4"',
        "        with:",
        f'          name: "{artifact["name"]}"',
        "          path: |",
    ]
    for path in artifact["paths"]:
        lines.append(f"            {path}")
    lines.append("")
    return lines


def _render_pages_upload_step(*, shared: dict[str, Any], workflow: dict[str, Any]) -> list[str]:
    pages = workflow.get("pages", {})
    if not pages.get("enabled"):
        return []

    lines = ['      - name: "Upload pages artifact"']
    if pages.get("upload_condition"):
        lines.append(f"        if: {pages['upload_condition']}")
    lines.extend(
        [
            '        uses: "actions/upload-pages-artifact@v3"',
            "        with:",
            f'          path: "{shared["pages"]["public_dir"]}"',
            "",
        ]
    )
    return lines


def _render_deploy_job(*, shared: dict[str, Any], workflow: dict[str, Any]) -> list[str]:
    deploy_condition = workflow["pages"]["deploy_condition"]
    environment_name = shared["pages"]["environment_name"]
    return [
        "  deploy:",
        "    needs: build",
        f"    if: {deploy_condition}",
        "    environment:",
        f'      name: "{environment_name}"',
        '      url: "${{ steps.deployment.outputs.page_url }}"',
        f'    runs-on: "{shared["runs_on"]}"',
        "    steps:",
        '      - name: "Deploy to GitHub Pages"',
        "        id: deployment",
        '        uses: "actions/deploy-pages@v4"',
    ]


def _render_mapping(*, workflow_value: dict[str, Any], indent: int) -> list[str]:
    lines: list[str] = []
    prefix = "  " * indent
    for key, value in workflow_value.items():
        if isinstance(value, bool):
            lines.append(f"{prefix}{key}: {_yaml_bool(value)}")
        else:
            lines.append(f"{prefix}{key}: {_yaml_scalar(value)}")
    return lines


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return _yaml_bool(value)
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace('"', '\\"')
    return f'"{text}"'


def _yaml_bool(value: bool) -> str:
    return "true" if value else "false"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate GitHub Actions workflows from config")
    parser.add_argument("--root-dir", default=".", help="Project root directory")
    parser.add_argument("--config", help="Path to config/github_actions.yml")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether workflows are up to date",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root_dir = Path(args.root_dir).resolve()
    config_path = Path(args.config).resolve() if args.config else None
    changed = sync_workflows(root_dir=root_dir, config_path=config_path, check=args.check)
    if args.check and changed:
        for path in changed:
            print(f"Out of date: {path.relative_to(root_dir)}")
        return 1
    for path in changed:
        print(f"Updated: {path.relative_to(root_dir)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
